DROP DATABASE IF EXISTS employees_db
CREATE DATABASE employees_db
USE employees_db

CREATE TABLE department (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE role(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30), UNIQUE NOT NULL,
    salary DECIMAL UNSIGNED NOT NULL
)